version: '3.5'

services:
  db:
    image: mysql:latest
    container_name: edcatalogo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: edcatalogo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      # - /etc/mysql/my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    # networks:
    #   - my_network

volumes:
  mysql_data:

# networks:
#   my_network:
#     driver: bridge